### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by breestealth** [bonfy/qiandao#2]
When I use this script, I got this message:

```
Traceback (most recent call last):
  File "v2ex.py", line 37, in <module>
    qiandao_v2ex()
  File "v2ex.py", line 32, in qiandao_v2ex
    resp = session.get('http://v2ex.com' + re.search(r'/mission/daily/redeem\?once=\d+', resp.text).group())
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by bonfy** [comment]
Thank you for using my `qiandao` script

1. Please confirm that you run it on Travis-CI and you have set the Environment Variables 
`v2ex_username`  and  `v2ex_password` Value correctly
2. Check your `v2ex_username`  and  `v2ex_password` again ,make sure that you can use them login directly from https://www.v2ex.com/
3. If you run the script in your local machine, please make sure that you have put your own username and password in the `v2ex.py`

```python
v2ex_username = os.getenv('v2ex_username')   # enter your own username
v2ex_password = os.getenv('v2ex_password')   # enter your own password
```

From your error log, I think your network is ok, but there's something wrong with your login. So please check your username and passord first.Thank you

**Comment by breestealth** [comment]
Maybe I have some special characters in my password? I will try to change my password and try again.

**Comment by breestealth** [comment]
I change the password and remove the special characters such as "%", and then I success.
So maybe the problem is the method of handle the special character % in the password.

**Comment by bonfy** [comment]
Thank you for reminding me the problem of special characters like '%'

``` python
In [1]: import urllib

In [2]: password = '%'

In [3]: urllib.parse.quote(password)
Out[3]: '%25'
```

May be you use `%25` replace `%` can handle the problem
I will try later and fix this bug

Thank you

**Comment by bonfy** [comment]
I try the password with character '%', it worked well in my environment

Mac & python 3.5

**Comment by breestealth** [comment]
Maybe some other characters lead to the problem.

My previously used password is `%cQXefE$zEUV3ns67qLB`, maybe you can try this password.

When I change the password to a string without any special character, the error disappeared.
